### ISSUE TITLE
Rust is bad... just saying.. from not so personal experience 

### ISSUE THREAD

**Issue by Sooryasanand** [brynblack/chess#11]
How to fix this error: 

DON'T USE RUST INSTEAD USE C++...

**Comment by brynblack** [comment]
Nah, ur all just mad because you don't have experience with Rust

You haven't taken the time to learn it, so how is it logical to base an opinion off of it?

**Comment by brynblack** [comment]
https://www.youtube.com/watch?v=03H1cWj2Kfc

**Comment by brynblack** [comment]
😄
